#!/usr/bin/env python3
"""runs-index.py — generate runs/INDEX.md, the visible track record of Abhidhamma-mode runs.

  scripts/runs-index.py           write runs/INDEX.md
  scripts/runs-index.py --check   exit 1 if runs/INDEX.md is stale (CI runs this)

Everything is DERIVED from the run directories — never typed by hand — so the record cannot drift from
the files it summarises. Verdicts are read from each RUN.md exactly as scored; failures are listed like
passes. A run with a RUN.md but no PREREG.md is RETROSPECTIVE and is never counted in the track record.
"""
import glob, os, re, subprocess, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.join(REPO, "runs")
OUT = os.path.join(RUNS, "INDEX.md")

def field(text, name):
    m = re.search(rf"\*\*{name}:\*\*\s*(.+)", text)
    return m.group(1).strip() if m else ""

def first_commit(path):
    r = subprocess.run(["git", "-C", REPO, "log", "--diff-filter=A", "--format=%h %cI", "--", os.path.relpath(path, REPO)],
                       capture_output=True, text=True).stdout.strip().splitlines()
    return r[-1] if r else "uncommitted"

def row(d):
    name = os.path.basename(d)
    pre, run = os.path.join(d, "PREREG.md"), os.path.join(d, "RUN.md")
    p = open(pre, encoding="utf-8").read() if os.path.exists(pre) else ""
    r = open(run, encoding="utf-8").read() if os.path.exists(run) else ""
    control = "CONTROL" in p.split("\n", 1)[0] if p else False
    if not p:
        kind, verdict = "retrospective", "—"
    else:
        kind = "control" if control else "run"
        m = re.search(r"VERDICT:?\**\s*\**\s*(PASS|FAIL)", r)
        verdict = m.group(1) if m else ("pending" if not r else "unscored")
    q = field(p, "Question") if p else (re.search(r"#\s*RUN\s*—\s*(.+?)(?:\s{2}|$)", r, re.M) or [None, ""])[1]
    window = field(p, "Window") if p else (re.search(r"\*\*Window:\*\*\s*([^·\n]+)", r) or [None, ""])[1].strip()
    prereg = first_commit(pre) if p else "not pre-registered"
    ots = "✓" if os.path.exists(pre + ".ots") else ("—" if not p else "✗")
    lean = sorted(os.path.basename(x) for x in glob.glob(os.path.join(d, "*.lean")))
    q = q if len(q) <= 110 else q[:107] + "…"
    return name, kind, verdict, window, prereg, ots, ", ".join(lean) or "—", q

def build():
    rows = [row(d) for d in sorted(glob.glob(os.path.join(RUNS, "2*"))) if os.path.isdir(d)]
    scored = [x for x in rows if x[1] in ("run", "control") and x[2] in ("PASS", "FAIL")]
    ctrl = [x for x in scored if x[1] == "control"]
    lines = [
        "# Abhidhamma-mode runs — the track record",
        "",
        "*GENERATED by `scripts/runs-index.py` from the run directories — never edit by hand; CI fails if it is stale.*",
        "",
        f"**Controls scored: {len(ctrl)} — {sum(x[2]=='PASS' for x in ctrl)} PASS · {sum(x[2]=='FAIL' for x in ctrl)} FAIL.** "
        f"Pre-registered runs scored: {len(scored)}. Retrospective (not pre-registered, never counted): "
        f"{sum(x[1]=='retrospective' for x in rows)}.",
        "",
        "A **control** is a case chosen because the texts should LOSE under the declared window; the mode passes only by",
        "reporting the collision plainly. Verdicts are copied from each `RUN.md` exactly as scored against its `PREREG.md`.",
        "`PREREG` = the commit that added the pre-registration (GitHub's activity record and the `.ots` proof date it",
        "independently). `OTS` = an OpenTimestamps proof sits beside the PREREG.",
        "",
        "| Run | Kind | Verdict | Window | PREREG commit | OTS | Lean | Question |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for n, k, v, w, pr, o, l, q in rows:
        lines.append(f"| [`{n}`]({n}/) | {k} | **{v}** | {w} | {pr} | {o} | {l} | {q.replace('|', '/')} |")
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("runs/INDEX.md is STALE — run scripts/runs-index.py and commit"); sys.exit(1)
        print("runs/INDEX.md is current"); sys.exit(0)
    open(OUT, "w", encoding="utf-8").write(text); print(text)
